#!/usr/bin/csh -f

echo php documentation generator
echo === ============= =========
set ugit = /usr/bin/git

echo go to the php source directory and set the name of the documentation folder
set docudir = docs
$ugit switch dev

echo clean that folder
sudo rm -fR $docudir
mkdir $docudir

echo the following command will generate the documentation if docker is installed
echo docker run --rm -v ${PWD}:/data phpdoc/phpdoc:3 -d . -t $docudir
docker run --rm -v ${PWD}:/data phpdoc/phpdoc:3 -d . -t $docudir

echo final info, git and clean
/usr/bin/du --max-depth=1 -h -a $docudir

$ugit commit -am 'php documentation'
$ugit push

unset docudir
unset ugit
