#!/usr/bin/csh -f

echo      ////////////////////////////////////////////////////
echo     /// php documentation generation and publication ///
echo    ////////// with phpdoc, docker and github //////////
echo   // code by Kaloyan KRASTEV, kaloyansen@gmail.com ///
echo  ////////////////// version 0.0.3 ///////////////////
echo ////////////////////////////////////////////////////
echo 0. usage: \
it is possible to follow the comments one by one but you may want to \
edit this file in a way needed by your project and then run it any time you need to

echo 1. set the git branch if needed
set ugit = /usr/bin/git
$ugit switch dev

echo 2. chose a php source and a documentation target directory \
docs is ok for github to generate web pages from the documentation
set srcdir = ${PWD}/src
set docdir = docs
set neuf = $srcdir/$docdir

echo 3. if you have docker the following long command is going to generate the documentation \
after/if the docker image has been dowloaded
set dockerun = /usr/bin/docker\ run\ --rm\ -v\ ${srcdir}:/data\ phpdoc/phpdoc:3\ -t\ $docdir
echo $dockerun
$dockerun
/usr/bin/sudo rm -fR $docdir
/usr/bin/sudo mv -fv $neuf .

echo 4. disk usage
/usr/bin/du --max-depth=1 -h -a $docdir
/usr/bin/find $srcdir -name "*.php" | xargs wc -l | sort -n

echo 5. save change and send it all to github
$ugit commit -am 'commit de la documentation générée par phpdoc:3'
$ugit push

echo 6. clean the envirenment
unset ugit
unset srcdir
unset docdir
unset neuf
unset dockerun
