<?php namespace view;
/**
 * @desc update article
 * @namespace view
 * @category view
 * @author Kaloyan KRASTEV
 * @link kaloyansen@gmail.com
 * @version 0.0.2
 */
class Update extends \view\Frontend {

	public function __construct($controbjet) {

		parent::__construct($controbjet);

		$ta = $controbjet->ticket_array;
		echo '<article>';
		self::viewMessage($controbjet->message);
		self::viewForm($ta[0], 'ticket', 'update_ticket_form_fill');
		echo '</article>';

		self::viewModal($controbjet->modal, 'de la base de données', 'merci');
	}

	private static function viewForm(\model\Ticket $ticket, string $dcl, string $name): void {

		$color = \Colors\RandomColor::one(array('luminosity'=>'light'));?>
  <div class="<?=$dcl;?>">

    <form method="post" action="">
      <p><input type="hidden" name="<?=$name;?>" value="true" /></p>
      <p><input id="title" type="text" name="title" value="<?=$ticket->getTitle();?>" /></p>
      <span class="titleErr"></span>
      <p><textarea id="body" name="body">autogenerated text to fill th body of this ticket because it need to have some text like poem or something important autogenerated text to fill th body of this ticket because it need to have some text like poem or something important autogenerated text to fill th body of this ticket because it need to have some text like poem or something important <?=$ticket->getBody() ?></textarea></p>
      <span class="bodyErr"></span>
      <p><input id="position" type="text" name="position" value="<?=$ticket->getPosition();?>" /></p>
      <span class="positionErr"></span>
      <p><input id="status" type="text" name="status" value="<?=$ticket->getStatus();?>" /></p>
      <span class="statusErr"></span>
      <p><input id="color" type="text" name="color" value="<?=$color;?>" style="background-color: <?=$color;?>;" /></p>
      <span class="colorErr"></span>
      <p><input id="description" type="text" name="description" value="<?=$ticket->getDescription();?>" /></p>
      <span class="descriptionErr"></span>
      <p><input id="keywords" type="text" name="keywords" value="<?=$ticket->getKeywords();?>" /></p>
      <span class="keywordsErr"></span>
	  <p><input id="submit" type="submit" value="update ticket" /></p>
	  <span class="submitErr"></span>
    </form>
  </div><?php
    }
} ?>



